# Generated by Django 3.1 on 2020-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(verbose_name='Date published')),
                ('average_rating', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('thumbnail', models.URLField(max_length=300)),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('categories', models.ManyToManyField(to='books.Category')),
            ],
        ),
    ]
